/*
    *Creo los el diccionario que a partir de tu seleccion te dira la abreviatura correspondiente
    *Dicha abreviatura será la que aparezca en el dibujo debajo de la linea analizada
    */
    var categorias = {
        //Etiquetas especiales para los puntos (Incognitas) de los ejercicios a resolver
        //'wyz1' : 'wyz1',
        //'wyz2' : 'wyz2',
        //'wyz3' : 'wyz3',
        //'wyz4' : 'wyz4',

        'op1' : 'op1',
        'op2' : 'op2',
        'op3' : 'op3',
        'op4' : 'op4',

        'Pronombre' : 'Pron',
        
        'Adjetivo': 'Adj',
        'Adverbio': 'Adv',
        'Adjunto periférico': 'AP',
        'Aposición': 'Apos',
        'Determinante': 'Det',
        'Enlace': 'E',
        'Preposición': 'Prep',
        'Construcción Preposicional': 'ConstPrep',
        'Cuantificador': "Cuant",
        'Grupo adjetival': 'GAdj',
        'Grupo adjetival / Adjunto Periférico': 'GAdj/AP',
        'Grupo adjetival / Atributo': 'GAdj/ATR',
        'Grupo adjetival / Complemento Circunstancial': 'GAdj/CC',
        'Grupo adjetival / Complemento Circunstancial Causa': 'GAdj/CCCausa',
        'Grupo adjetival / Complemento Circunstancial Lugar': 'GAdj/CCL',
        'Grupo adjetival / Complemento Circunstancial Modo': 'GAdj/CCM',
        'Grupo adjetival / Complemento Circunstancial Tiempo': 'GAdj/CCTmp',
        'Grupo adjetival / Complemento Directo': 'GAdj/CD',
        'Grupo adjetival / Complemento del Nombre': 'GAdj/CN',
        'Grupo adjetival / MP': 'GAdj/MP',
        'Grupo adjetival / Complemento Predicativo': 'GAdj/PVO',
        'Grupo adjetival / Término': 'GAdj/T',
        'Grupo adjetival / Vocativo': 'GAdj/Voc',

        'Grupo adverbial': 'GAdv',
        'Grupo adverbial / Adjunto Periférico': 'GAdv/AP',
        'Grupo adverbial / Atributo': 'GAdv/ATR',
        'Grupo adverbial / Complemento Circunstancial': 'GAdv/CC',
        'Grupo adverbial / Complemento Circunstancial Cantidad': 'GAdv/CCCant',
        'Grupo adverbial / Complemento Circunstancial Causa': 'GAdv/CCCausa',
        'Grupo adverbial / Complemento Circunstancial Lugar': 'GAdv/CCL',
        'Grupo adverbial / Complemento Circunstancial Modo': 'GAdv/CCM',
        'Grupo adverbial / Complemento Circunstancial Tiempo': 'GAdv/CCTmp',
        'Grupo adverbial / Complemento Directo': 'GAdv/CD',
        'Grupo adverbial / Complemento del Nombre': 'GAdv/CN',
        'Grupo adverbial / Complemento de Régimen': 'GAdv/CR',
        'Grupo adverbial / MP': 'GAdv/MP',
        'Grupo adverbial / Complemento Predicativo': 'GAdv/PVO',
        'Grupo adverbial / Sujeto': 'GAdv/S',
        'Grupo adverbial / Término': 'GAdv/T',

        'Grupo nominal': 'GN',
        'Grupo nominal / Aposición': 'GN/Apos',
        'Grupo nominal / Adjunto Periférico': 'GN/AP',
        'Grupo nominal / Atributo': 'GN/ATR',
        'Grupo nominal / Complemento Circunstancial': 'GN/CC',
        'Grupo nominal / Complemento Circunstancial Cantidad': 'GN/CCCant',
        'Grupo nominal / Complemento Circunstancial Causa': 'GN/CCCausa',
        'Grupo nominal / Complemento Circunstancial Lugar': 'GN/CCL',
        'Grupo nominal / Complemento Circunstancial Modo': 'GN/CCM',
        'Grupo nominal / Complemento Circunstancial Tiempo': 'GN/CCTmp',
        'Grupo nominal / Complemento Directo': 'GN/CD',
        'Grupo nominal / Complemento Indirecto': 'GN/CI',
        'Grupo nominal / Complemento de Régimen': 'GN/CR',
        'Grupo nominal / Complemento Predicativo': 'GN/PVO',
        'Grupo nominal / Sujeto': 'GN/S',
        'Grupo nominal / Término': 'GN/T',
        'Grupo nominal / Vocativo': 'GN/Voc',

        'Grupo preposicional': 'GPrep',
        'Grupo preposicional / Adjunto Periférico': 'GPrep/AP',
        'Grupo preposicional / Atributo': 'GPrep/ATR',
        'Grupo preposicional / Complemento del Adjetivo': 'GPrep/CAdj',
        'Grupo preposicional / Complemento Agente': 'GPrep/CAg',
        'Grupo preposicional / Complemento Circunstancial': 'GPrep/CC',
        'Grupo preposicional / Complemento Circunstancial Cantidad': 'GPrep/CCCant',
        'Grupo preposicional / Complemento Circunstancial Causa': 'GPrep/CCCausa',
        'Grupo preposicional / Complemento Circunstancial Finalidad': 'GPrep/CCFin',
        'Grupo preposicional / Complemento Circunstancial Compañía': 'GPrep/CCComp',
        'Grupo preposicional / Complemento Circunstancial Instrumento': 'GPrep/CCInstr',
        'Grupo preposicional / Complemento Circunstancial Lugar': 'GPrep/CCL',
        'Grupo preposicional / Complemento Circunstancial Modo': 'GPrep/CCM',
        'Grupo preposicional / Complemento Circunstancial Tema': 'GPrep/CCTema',
        'Grupo preposicional / Complemento Circunstancial Tiempo': 'GPrep/CCTmp',
        'Grupo preposicional / Complemento Directo': 'GPrep/CD',
        'Grupo preposicional / Complemento Indirecto': 'GPrep/CI',
        'Grupo preposicional / Complemento del Nombre': 'GPrep/CN',
        'Grupo preposicional / Complemento de Régimen': 'GPrep/CR',
        'Grupo preposicional / MP': 'GPrep/MP',
        'Grupo preposicional / Complemento Predicativo': 'GPrep/PVO',
        'Grupo preposicional / Sujeto': 'GPrep/S',
        'Grupo preposicional / Término': 'GPrep/T',
        'Grupo verbal': 'GV',
        'Grupo verbal / Predicado nominal': 'GV/PN',
        'Grupo verbal / Predicado verbal': 'GV/PV',
        'Interjección': 'Interj',
        'MImp': 'MImp',
        'MN': 'MN',
        'Núcleo': 'N',
        'Núcleo Predicado': 'NP',
        'Oración': 'O',
        'Oración Compuesta': 'O.Compuesta',
        'Oración Simple': 'O.Simple',
        'Oración / Adjunto Periférico': 'O/AP',
        'Oración / Atributo': 'O/ATR',
        'Oración / Complemento Circunstancial de Tiempo': 'O/CCTmp',
        'Oración / Complemento Directo': 'O/CD',
        'Oración / Complemento del Nombre': 'O/CN',
        'Oración / Sujeto': 'O/S',

        'Oración Subordinada': 'OS',
        'Oración Subordinada / Adjunto Periférico': 'OS/AP',
        'Oración Subordinada / Atributo': 'OS/ATR',
        'Oración Subordinada / Complemento del Adjetivo': 'OS/CAdj',
        'Oración Subordinada / Complemento Agente': 'OS/CAg',
        'Oración Subordinada / Complemento Circunstancial': 'OS/CC',
        'Oración Subordinada / Complemento Circunstancial Cantidad': 'OS/CCCant',
        'Oración Subordinada / Complemento Circunstancial Causa': 'OS/CCCausa',
        'Oración Subordinada / Complemento Circunstancial Finalidad': 'OS/CCFin',
        'Oración Subordinada / Complemento Circunstancial Instrumento': 'OS/CCInstr',
        'Oración Subordinada / Complemento Circunstancial Lugar': 'OS/CCL',
        'Oración Subordinada / Complemento Circunstancial Modo': 'OS/CCM',
        'Oración Subordinada / Complemento Circunstancial Tema': 'OS/CCTema',
        'Oración Subordinada / Complemento Circunstancial Tiempo': 'OS/CCTmp',
        'Oración Subordinada / Complemento Directo': 'OS/CD',
        'Oración Subordinada / Complemento Indirecto': 'OS/CI',
        'Oración Subordinada / Complemento del Nombre': 'OS/CN',
        'Oración Subordinada / Complemento de Régimen': 'OS/CR',
        'Oración Subordinada / MP': 'OS/MP',
        'Oración Subordinada / Complemento Predicativo': 'OS/PVO',
        'Oración Subordinada / Sujeto': 'OS/S',

        'Pasiva Refleja': 'PasRef',
        'Punto': 'Punt',
        'Sujeto Omitido': 'SO',

        'Nexo': 'Nx',
        'Nexo / Atributo': 'Nx/ATR',
        'Nexo / Complemento Agente': 'Nx/CAg',
        'Nexo / Complemento Circunstancial': 'Nx/CC',
        'Nexo / Complemento Circunstancial Cantidad': 'Nx/CCCant',
        'Nexo / Complemento Circunstancial Causa': 'Nx/CCCausa',
        'Nexo / Complemento Circunstancial Finalidad': 'Nx/CCFin',
        'Nexo / Complemento Circunstancial Lugar': 'Nx/CCL',
        'Nexo / Complemento Circunstancial Modo': 'Nx/CCM',
        'Nexo / Complemento Circunstancial Tema': 'Nx/CCTema',
        'Nexo / Complemento Circunstancial Tiempo': 'Nx/CCTmp',
        'Nexo / Complemento Directo': 'Nx/CD',
        'Nexo / Complemento Indirecto': 'Nx/CI',
        'Nexo / Complemento del Nombre': 'Nx/CN',
        'Nexo / Complemento de Régimen': 'Nx/CR',
        'Nexo / Sujeto': 'Nx/S',

        'Oración coordinada copulativa': 'O.C Cop',
        'Oración coordinada disyuntivas': 'O.C Disy',
        'Oración coordinada adversativas': 'O.C Adv',
        'Oración coordinada yuxtapuesta': 'O.C Yuxt',
        'Oración subordinada de relativo': 'OS.Relativo',

        'Construcción temporal externa / Adjunto Periférico': 'Const Temp Ex/AP',
        'Construcción causal externa / Adjunto Periférico': 'Const Caus Ex/AP',
        'Construcción final externa / Adjunto Periférico': 'Const Fin Ex/AP',
        'Construcción ilativa externa / Adjunto Periférico': 'Const Ilat Ex/AP',
        'Construcción condicional externa / Adjunto Periférico': 'Const Cond Ex/AP',
        'Construcción concesiva externa externa / Adjunto Periférico': 'Const Conc Ex/AP',
  

        'Construcción temporal Interna / Complemento Circunstancial de Tiempo': 'Const Temp In/CCT',
        'Construcción causal Interna / Complemento Circunstancial de Causa': 'Const Caus In/CCCausa',
        'Construcción final Interna / Complemento Circunstancial de finalidad': 'Const Fin In/CCFin',
        'Construcción ilativa Interna / Complemento Circunstancial': 'Const Ilat In/CC',
        'Construcción concesiva Interna / Complemento Circunstancial de concesión': 'Const Conc In/CCConc',

        'Construcción condicional': 'Const Cond',
        'Construcción consecutiva': 'Const Cons',
        'Construcción comparativa': 'Const Comp',
        'Construcción superlativa': 'Const Sup',

        'Oración Subordinada sustantiva': 'OS.Sustantiva',
        'Subordinada sustantiva en función de complemento directo': 'OS.Sustantiva/CD',
        'Subordinada sustantiva en función de sujeto': 'OS.Sustantiva/S',
        'Subordinada sustantiva en función de complemento de régimen': 'OS.Sustantiva/CR',
        'Subordinada sustantiva en función de Adjunto Periférico': 'OS.Sustantiva/AP',
        'Subordinada sustantiva en función de termino': 'OS.Sustantiva/T',
        'Subordinada sustantiva en función de complemento circunstancial': 'OS.Sustantiva/CC',
        'Subordinada sustantiva en función de complemento circunstancial lugar': 'OS.Sustantiva/CCL',
        'Subordinada sustantiva en función de complemento circunstancial tiempo': 'OS.Sustantiva/CCTmp',
        'Subordinada sustantiva en función de atributo': 'OS.Sustantiva/ATR',
        'Subordinada sustantiva en función de complemento predicativo': 'OS.Sustantiva/PVO',

        'Subordinada de relativo con antecedente expreso': 'OS.Relativo AntExp',
        'Subordinada de relativo sin antecedente expreso': 'OS.Relativo  sin AntExp',
        'Subordinada de relativo con antecedente expreso especificativas': 'OS.Relativo AntExp Esp',
        'Subordinada de relativo con antecedente expreso explicativas': 'OS.Relativo AntExp Expl',
        'Subordinada de relativo sin antecedente expreso libre': 'OS.Relativo sin AntExp Lib',
        'Subordinada de relativo sin antecedente expreso semilibre': 'OS.Relativo sin AntExp Semlib',


        'Subordinada de relativo con antecedente expreso': 'OS.Relativo AntExp',
        'Subordinada de relativo con antecedente expreso / Sujeto': 'OS.Relativo AntExp/S',
        'Subordinada de relativo con antecedente expreso / Adjunto Periférico': 'OS.Relativo AntExp/AP',
        'Subordinada de relativo con antecedente expreso / Atributo': 'OS.Relativo AntExp/ATR',
        'Subordinada de relativo con antecedente expreso / Complemento del Adjetivo': 'OS.Relativo AntExp/CAdj',
        'Subordinada de relativo con antecedente expreso / Complemento Agente': 'OS.Relativo AntExp/CAg',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial': 'OS.Relativo AntExp/CC',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Cantidad': 'OS.Relativo AntExp/CCCant',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Causa': 'OS.Relativo AntExp/CCCausa',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Finalidad': 'OS.Relativo AntExp/CCFin',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Instrumento': 'OS.Relativo AntExp/CCInstr',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Lugar': 'OS.Relativo AntExp/CCL',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Modo': 'OS.Relativo AntExp/CCM',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Tema': 'OS.Relativo AntExp/CCTema',
        'Subordinada de relativo con antecedente expreso / Complemento Circunstancial Tiempo': 'OS.Relativo AntExp/CCTmp',
        'Subordinada de relativo con antecedente expreso / Complemento Directo': 'OS.Relativo AntExp/CD',
        'Subordinada de relativo con antecedente expreso / Complemento Indirecto': 'OS.Relativo AntExp/CI',
        'Subordinada de relativo con antecedente expreso / Complemento del Nombre': 'OS.Relativo AntExp/CN',
        'Subordinada de relativo con antecedente expreso / Complemento de Régimen': 'OS.Relativo AntExp/CR',
        'Subordinada de relativo con antecedente expreso / MP': 'OS.Relativo AntExp/MP',
        'Subordinada de relativo con antecedente expreso / Complemento Predicativo': 'OS.Relativo AntExp/PVO',
        'Subordinada de relativo con antecedente expreso especificativas': 'OS.Relativo AntExp Esp',
        'Subordinada de relativo con antecedente expreso especificativas / Sujeto': 'OS.Relativo AntExp Esp/S',
        'Subordinada de relativo con antecedente expreso especificativas / Adjunto Periférico': 'OS.Relativo AntExp Esp/AP',
        'Subordinada de relativo con antecedente expreso especificativas / Atributo': 'OS.Relativo AntExp Esp/ATR',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento del Adjetivo': 'OS.Relativo AntExp Esp/CAdj',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Agente': 'OS.Relativo AntExp Esp/CAg',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial': 'OS.Relativo AntExp Esp/CC',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Cantidad': 'OS.Relativo AntExp Esp/CCCant',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Causa': 'OS.Relativo AntExp Esp/CCCausa',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Finalidad': 'OS.Relativo AntExp Esp/CCFin',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Instrumento': 'OS.Relativo AntExp Esp/CCInstr',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Lugar': 'OS.Relativo AntExp Esp/CCL',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Modo': 'OS.Relativo AntExp Esp/CCM',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Tema': 'OS.Relativo AntExp Esp/CCTema',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Circunstancial Tiempo': 'OS.Relativo AntExp Esp/CCTmp',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Directo': 'OS.Relativo AntExp Esp/CD',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Indirecto': 'OS.Relativo AntExp Esp/CI',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento del Nombre': 'OS.Relativo AntExp Esp/CN',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento de Régimen': 'OS.Relativo AntExp Esp/CR',
        'Subordinada de relativo con antecedente expreso especificativas / MP': 'OS.Relativo AntExp Esp/MP',
        'Subordinada de relativo con antecedente expreso especificativas / Complemento Predicativo': 'OS.Relativo AntExp Esp/PVO',
        'Subordinada de relativo con antecedente expreso explicativas': 'OS.Relativo AntExp Expl',
        'Subordinada de relativo con antecedente expreso explicativas / Sujeto': 'OS.Relativo AntExp Expl/S',
        'Subordinada de relativo con antecedente expreso explicativas / Adjunto Periférico': 'OS.Relativo AntExp Expl/AP',
        'Subordinada de relativo con antecedente expreso explicativas / Atributo': 'OS.Relativo AntExp Expl/ATR',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento del Adjetivo': 'OS.Relativo AntExp Expl/CAdj',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Agente': 'OS.Relativo AntExp Expl/CAg',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial': 'OS.Relativo AntExp Expl/CC',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Cantidad': 'OS.Relativo AntExp Expl/CCCant',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Causa': 'OS.Relativo AntExp Expl/CCCausa',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Finalidad': 'OS.Relativo AntExp Expl/CCFin',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Instrumento': 'OS.Relativo AntExp Expl/CCInstr',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Lugar': 'OS.Relativo AntExp Expl/CCL',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Modo': 'OS.Relativo AntExp Expl/CCM',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Tema': 'OS.Relativo AntExp Expl/CCTema',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Circunstancial Tiempo': 'OS.Relativo AntExp Expl/CCTmp',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Directo': 'OS.Relativo AntExp Expl/CD',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Indirecto': 'OS.Relativo AntExp Expl/CI',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento del Nombre': 'OS.Relativo AntExp Expl/CN',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento de Régimen': 'OS.Relativo AntExp Expl/CR',
        'Subordinada de relativo con antecedente expreso explicativas / MP': 'OS.Relativo AntExp Expl/MP',
        'Subordinada de relativo con antecedente expreso explicativas / Complemento Predicativo': 'OS.Relativo AntExp Expl/PVO',
        'Subordinada de relativo sin antecedente expreso': 'OS.Relativo sin AntExp',
        'Subordinada de relativo sin antecedente expreso / Sujeto': 'OS.Relativo sin AntExp/S',
        'Subordinada de relativo sin antecedente expreso / Adjunto Periférico': 'OS.Relativo sin AntExp/AP',
        'Subordinada de relativo sin antecedente expreso / Atributo': 'OS.Relativo sin AntExp/ATR',
        'Subordinada de relativo sin antecedente expreso / Complemento del Adjetivo': 'OS.Relativo sin AntExp/CAdj',
        'Subordinada de relativo sin antecedente expreso / Complemento Agente': 'OS.Relativo sin AntExp/CAg',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial': 'OS.Relativo sin AntExp/CC',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Cantidad': 'OS.Relativo sin AntExp/CCCant',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Causa': 'OS.Relativo sin AntExp/CCCausa',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Finalidad': 'OS.Relativo sin AntExp/CCFin',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Instrumento': 'OS.Relativo sin AntExp/CCInstr',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Lugar': 'OS.Relativo sin AntExp/CCL',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Modo': 'OS.Relativo sin AntExp/CCM',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Tema': 'OS.Relativo sin AntExp/CCTema',
        'Subordinada de relativo sin antecedente expreso / Complemento Circunstancial Tiempo': 'OS.Relativo sin AntExp/CCTmp',
        'Subordinada de relativo sin antecedente expreso / Complemento Directo': 'OS.Relativo sin AntExp/CD',
        'Subordinada de relativo sin antecedente expreso / Complemento Indirecto': 'OS.Relativo sin AntExp/CI',
        'Subordinada de relativo sin antecedente expreso / Complemento del Nombre': 'OS.Relativo sin AntExp/CN',
        'Subordinada de relativo sin antecedente expreso / Complemento de Régimen': 'OS.Relativo sin AntExp/CR',
        'Subordinada de relativo sin antecedente expreso / MP': 'OS.Relativo sin AntExp/MP',
        'Subordinada de relativo sin antecedente expreso / Complemento Predicativo': 'OS.Relativo sin AntExp/PVO',
        'Subordinada de relativo sin antecedente expreso libre': 'OS.Relativo sin AntExp Lib',
        'Subordinada de relativo sin antecedente expreso libre / Sujeto': 'OS.Relativo sin AntExp Lib/S',
        'Subordinada de relativo sin antecedente expreso libre / Adjunto Periférico': 'OS.Relativo sin AntExp Lib/AP',
        'Subordinada de relativo sin antecedente expreso libre / Atributo': 'OS.Relativo sin AntExp Lib/ATR',
        'Subordinada de relativo sin antecedente expreso libre / Complemento del Adjetivo': 'OS.Relativo sin AntExp Lib/CAdj',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Agente': 'OS.Relativo sin AntExp Lib/CAg',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial': 'OS.Relativo sin AntExp Lib/CC',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Cantidad': 'OS.Relativo sin AntExp Lib/CCCant',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Causa': 'OS.Relativo sin AntExp Lib/CCCausa',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Finalidad': 'OS.Relativo sin AntExp Lib/CCFin',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Instrumento': 'OS.Relativo sin AntExp Lib/CCInstr',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Lugar': 'OS.Relativo sin AntExp Lib/CCL',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Modo': 'OS.Relativo sin AntExp Lib/CCM',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Tema': 'OS.Relativo sin AntExp Lib/CCTema',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Circunstancial Tiempo': 'OS.Relativo sin AntExp Lib/CCTmp',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Directo': 'OS.Relativo sin AntExp Lib/CD',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Indirecto': 'OS.Relativo sin AntExp Lib/CI',
        'Subordinada de relativo sin antecedente expreso libre / Complemento del Nombre': 'OS.Relativo sin AntExp Lib/CN',
        'Subordinada de relativo sin antecedente expreso libre / Complemento de Régimen': 'OS.Relativo sin AntExp Lib/CR',
        'Subordinada de relativo sin antecedente expreso libre / MP': 'OS.Relativo sin AntExp Lib/MP',
        'Subordinada de relativo sin antecedente expreso libre / Complemento Predicativo': 'OS.Relativo sin AntExp Lib/PVO',
        'Subordinada de relativo sin antecedente expreso semilibre': 'OS.Relativo sin AntExp Semlib',
        'Subordinada de relativo sin antecedente expreso semilibre / Sujeto': 'OS.Relativo sin AntExp Semlib/S',
        'Subordinada de relativo sin antecedente expreso semilibre / Adjunto Periférico': 'OS.Relativo sin AntExp Semlib/AP',
        'Subordinada de relativo sin antecedente expreso semilibre / Atributo': 'OS.Relativo sin AntExp Semlib/ATR',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento del Adjetivo': 'OS.Relativo sin AntExp Semlib/CAdj',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Agente': 'OS.Relativo sin AntExp Semlib/CAg',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial': 'OS.Relativo sin AntExp Semlib/CC',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Cantidad': 'OS.Relativo sin AntExp Semlib/CCCant',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Causa': 'OS.Relativo sin AntExp Semlib/CCCausa',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Finalidad': 'OS.Relativo sin AntExp Semlib/CCFin',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Instrumento': 'OS.Relativo sin AntExp Semlib/CCInstr',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Lugar': 'OS.Relativo sin AntExp Semlib/CCL',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Modo': 'OS.Relativo sin AntExp Semlib/CCM',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Tema': 'OS.Relativo sin AntExp Semlib/CCTema',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Circunstancial Tiempo': 'OS.Relativo sin AntExp Semlib/CCTmp',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Directo': 'OS.Relativo sin AntExp Semlib/CD',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Indirecto': 'OS.Relativo sin AntExp Semlib/CI',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento del Nombre': 'OS.Relativo sin AntExp Semlib/CN',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento de Régimen': 'OS.Relativo sin AntExp Semlib/CR',
        'Subordinada de relativo sin antecedente expreso semilibre / MP': 'OS.Relativo sin AntExp Semlib/MP',
        'Subordinada de relativo sin antecedente expreso semilibre / Complemento Predicativo': 'OS.Relativo sin AntExp Semlib/PVO',

        'Término': 'T(GN)',

    };

    export default categorias;